### ISSUE TITLE
Minimize to tray does not remove program from ALT+Tab

### ISSUE THREAD

**Issue by jabcreations** [rafcolson/ClearStandbyMemoryScheduler#1]
Greetings. Simple: anything minimized to tray is removed from the ALT+Tab menu and ClearStandbyMemoryScheduler isn't. There is no point in having it visible to be selected since it's functionality is passive and warrants little-to-no further interaction once the shortcut to it has been placed in the Start Menu's Startup folder.

**Comment by rafcolson** [comment]
Could reproduce. Thanks for mentioning it. Didn't notice it before. Probably because this issue is not showing after restarting the system with the _Run at startup_ option enabled.

I will be looking at it this weekend, but feel free to Pull Requests.

**Comment by rafcolson** [comment]
@jabcreations The problem should be fixed. If it is, please close this issue. Download the latest release [here](https://github.com/rafcolson/ClearStandbyMemoryScheduler/releases).

**Comment by jabcreations** [comment]
ROCK! Done! Closed! Thank you!
