### ISSUE TITLE
Close button does not minimize to tray

### ISSUE THREAD

**Issue by jabcreations** [rafcolson/ClearStandbyMemoryScheduler#2]
Greetings! So when the minimize to tray option is enabled clicking the close button closes the program outright. This is counter-intuitive as the need for this program is high and there is no purpose to accidentally closing the program outright. If one desired to actually close it (while it's set to minimize to tray) then a couple extra clicks would be fully justified.

**Comment by rafcolson** [comment]
> This is counter-intuitive

True. I'll have a look at it this weekend.

**Comment by rafcolson** [comment]
@jabcreations The problem should be fixed. If it is, please close this issue. Download the latest release [here](https://github.com/rafcolson/ClearStandbyMemoryScheduler/releases).

**Comment by jabcreations** [comment]
ROCK! Done! Closed! Thank you!
