### ISSUE TITLE
Program won't install over itself after uninstalled

### ISSUE THREAD

**Issue by jabcreations** [rafcolson/ClearStandbyMemoryScheduler#4]
Just a quick error report dump. It looks like the installer doesn't yet know how to install over itself. It's a very reasonably specific name so I think you'd be safe to override the error-checking and install any way. For clarification I did not restart Windows or sign out/in first.

`PLATFORM VERSION INFO
	Windows 			: 10.0.19045.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9195.0 built by: NET481REL1LAST_B
	clr.dll 			: 4.8.9195.0 built by: NET481REL1LAST_B
	dfdll.dll 			: 4.8.9195.0 built by: NET481REL1LAST_B
	dfshim.dll 			: 10.0.19041.30000 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///D:/My%20Documents/Downloads/ClearStandbyMemoryScheduler%20App%20Install/ClearStandbyMemoryScheduler.application
	Application url			: file:///D:/My%20Documents/Downloads/ClearStandbyMemoryScheduler%20App%20Install/Application%20Files/ClearStandbyMemoryScheduler_1_0_0_1/ClearStandbyMemoryScheduler.exe.manifest

IDENTITIES
	Deployment Identity		: ClearStandbyMemoryScheduler.application, Version=1.0.0.1, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil
	Application Identity		: ClearStandbyMemoryScheduler.exe, Version=1.0.0.1, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\My Documents\Downloads\ClearStandbyMemoryScheduler App Install\ClearStandbyMemoryScheduler.application resulted in exception. Following failure messages were detected:
		+ Unable to install this application because an application with the same identity is already installed. To install this application, either modify the manifest version for this application or uninstall the preexisting application.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [12/23/2024 9:44:25 AM] : Activation of D:\My Documents\Downloads\ClearStandbyMemoryScheduler App Install\ClearStandbyMemoryScheduler.application has started.
	* [12/23/2024 9:44:25 AM] : Processing of deployment manifest has successfully completed.
	* [12/23/2024 9:44:25 AM] : Installation of the application has started.
	* [12/23/2024 9:44:25 AM] : Processing of application manifest has successfully completed.
	* [12/23/2024 9:44:28 AM] : Found compatible runtime version 4.0.30319.
	* [12/23/2024 9:44:28 AM] : Request of trust and detection of platform is complete.
	* [12/23/2024 9:44:28 AM] : Downloading of subscription dependencies is complete.
	* [12/23/2024 9:44:28 AM] : Commit of the downloaded application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12/23/2024 9:44:28 AM] System.Deployment.Application.DeploymentException (Subscription)
		- Unable to install this application because an application with the same identity is already installed. To install this application, either modify the manifest version for this application or uninstall the preexisting application.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SubscriptionStore.CheckApplicationPayload(CommitApplicationParams commitParams)
			at System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

`

**Comment by jabcreations** [comment]
Also I did explicitly exit the program on a second attempt to make sure it's not a problem with it still running thus blocking the install.

**Comment by jabcreations** [comment]
I signed off and signed back on to see if that would fix the installer. So then the program opened back up!

So the uninstaller (Windows Control Panel "Programs and Features",  not "settings app" garbage) failed to uninstall which I guess is another issue (sorry man).

The program runs from the registry and the executable is located here:

c:\users\john\appdata\local\apps\2.0\pwhykwve.nn1\hxa4rhdl.nyh\clea..tion_0000000000000000_0001.0000_90e23d48f06eff06\clearstandbymemoryscheduler.exe

**Comment by jabcreations** [comment]
Damn, I was about to manually remove it though when I minimized it the program did the 1.0.0 behavior...because it is 1.0.0! So the installer created a second version folder:

1.0.0.1?:
C:\Users\John\AppData\Local\Apps\2.0\PWHYKWVE.NN1\HXA4RHDL.NYH\clea...exe_0000000000000000_0001.0000_none_68b400649c412da1

1.0.0.0:
C:\Users\John\AppData\Local\Apps\2.0\PWHYKWVE.NN1\HXA4RHDL.NYH\clea..tion_0000000000000000_0001.0000_90e23d48f06eff06

If no one tells you then you don't know it needs to be fixed.

Are you using C or something like .NET?

**Comment by rafcolson** [comment]
Can reproduce on Windows 10, but not on Windows 11. The issue will not persist once you uninstall the application first and install the latest version. After that installing over it does not cause any issues. I guess this issue was caused by conflicting versions. The previous v1.0.0.1 you had installed and the latest v1.0.0.1 have the same id.  It would have been better to draft a new version for issue #3, I suppose. Sorry for that.

So uninstall the application, then reinstall. Then try reinstalling again and it should not give any errors. Let me know if that works.

**Comment by rafcolson** [comment]
> Are you using C or something like .NET?

In the right column of the app page you will find the programming languages for that app. The app is written in C# using .NET Framework 4.7.2.

**Comment by jabcreations** [comment]
I manually deleted everything in the following directory:
C:\Users\John\AppData\Local\Apps\2.0

That then allowed the second installer to function; hopefully that helps you out somehow.

**Comment by rafcolson** [comment]
It only confirms that the previous v1.0.0.1 you had installed and the latest v1.0.0.1 had the same id and were conflicting. So there is no issue anymore.
